// Metro cannot resolve a path it only learns at runtime, so a native build
// needs every recording spelled out in a require(). Generated from the same
// word list the recordings were rendered from — rerun after tts-build.js.
//
// Usage: node scripts/tts-map.js
const fs = require('fs');
const path = require('path');

const words = require(path.join(__dirname, '..', 'assets', 'words.json'));
const dir = path.join(__dirname, '..', 'public', 'audio');
// Same keys the app asks for: the headword, and "ex/<headword>" for its
// example sentence.
const keys = [...words.map(({ word }) => word), ...words.map(({ word }) => `ex/${word}`)];
const have = keys.filter((key) => fs.existsSync(path.join(dir, `${key}.mp3`)));

const lines = have.map((key) => `  '${key}': require('../../public/audio/${key}.mp3'),`);
const file = `// Generated by scripts/tts-map.js — do not edit by hand.
//
// The web build never loads this: recordings.web.ts stands in for it, because
// on web the same files are served straight out of public/audio as URLs and
// bundling them again would double the download.
export const recordings: Record<string, number> = {
${lines.join('\n')}
};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'lib', 'recordings.ts'), file);
console.log(`寫入 ${have.length} 筆（單字 ${words.length} 個，含例句最多 ${keys.length} 筆）`);
